web:
  - View
  - Assets
  - Gitignore
  - Env
  - Dir
  - Test
  - Gems
  - Deployment
  - Devise
  - Uncomment
  - Branch
  - Duplicate
  - Readme
api:
  - View
  - Assets
  - Gitignore
  - Env
  - Dir
  - Test
  - Gems
  - Deployment
  - Devise
  - Uncomment
  - Branch
  - Duplicate
  - Readme
